return {
    BinarySearch = require(script:WaitForChild("BinarySearch"));
    Cut = require(script:WaitForChild("Cut"));
    Filter = require(script:WaitForChild("Filter"));
    FoldLeft = require(script:WaitForChild("FoldLeft"));
    FoldRight = require(script:WaitForChild("FoldRight"));
    GroupBy = require(script:WaitForChild("GroupBy"));
    Insert = require(script:WaitForChild("Insert"));
    IsArray = require(script:WaitForChild("IsArray"));
    IsOrdered = require(script:WaitForChild("IsOrdered"));
    IsPureArray = require(script:WaitForChild("IsPureArray"));
    Map = require(script:WaitForChild("Map"));
    Merge = require(script:WaitForChild("Merge"));
    MergeMany = require(script:WaitForChild("MergeMany"));
    MutableBinaryInsert = require(script:WaitForChild("MutableBinaryInsert"));
    MutableMerge = require(script:WaitForChild("MutableMerge"));
    MutableMergeMany = require(script:WaitForChild("MutableMergeMany"));
    MutableReverse = require(script:WaitForChild("MutableReverse"));
    MutableShuffle = require(script:WaitForChild("MutableShuffle"));
    Remove = require(script:WaitForChild("Remove"));
    Reverse = require(script:WaitForChild("Reverse"));
    SelectFirst = require(script:WaitForChild("SelectFirst"));
    SelectLast = require(script:WaitForChild("SelectLast"));
    SelectRandom = require(script:WaitForChild("SelectRandom"));
    SelectWeighted = require(script:WaitForChild("SelectWeighted"));
    Shuffle = require(script:WaitForChild("Shuffle"));
    Sort = require(script:WaitForChild("Sort"));
};